name: Lint and Test

on: pull_request

jobs:
  Lint-and-Test:
    name: Lint code and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm install
      - run: npm run lint
      - run: npm test
